# .github/workflows/ci-docker.yml
name: Build and Push Docker Image

on:
  push:
    branches: ["main"]
    paths:
      - "docker/Dockerfile"
      - "**/*.go"
      - ".github/workflows/ci-docker.yml"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: eu-west-2
      AWS_ACCOUNT_ID: "595552412690"
      ECR_REPO: "new-memos-app"
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::595552412690:role/ECSCICDRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -f docker/Dockerfile -t ${ECR_REPO}:${IMAGE_TAG} .

      - name: Tag image for ECR
        run: |
          docker tag ${ECR_REPO}:${IMAGE_TAG} \
            ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}

      - name: Push image to ECR
        run: |
          docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}
